api_version = "unstable"

[[extensions]]
type = "ui_extension"
name = "action-menu-extension-react"
handle = "action-menu-extension-react"

# [START config.setup-targets]
[[extensions.targeting]]
module = "./src/MenuActionExtension.tsx"
target = "customer-account.order.action.menu-item.render"

[[extensions.targeting]]
module = "./src/MenuActionModalExtension.tsx"
target = "customer-account.order.action.render"
# [END config.setup-targets]