api_version = "unstable"

[[extensions]]
type = "ui_extension"
name = "ca-wishlist-js-profile-block"
handle = "ca-wishlist-js-profile-block"

[[extensions.targeting]]
module = "./src/ProfileBlockExtension.ts"
target = "customer-account.profile.block.render"
