# ...

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
# [START config.setup-scopes]
scopes = "customer_read_customers,customer_write_customers,write_customers"
# [END config.setup-scopes]

# ...
