api_version = "2025-10"

[[extensions]]
name = "localize-example"
handle = "localize-example"
type = "ui_extension"
uid = "e0260bd4-f328-fedf-994f-bfeb7e42f14a9089f017"

# [START config.setup-targets]
[[extensions.targeting]]
module = "./src/LocalizeExtension.jsx"
target = "customer-account.profile.block.render"
# [END config.setup-targets]

[extensions.capabilities]
api_access = true
