# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "7354ceacf8f0bb4b9ba112c83b5edf2f"
name = "collection-deeplinking"
handle = "collection-deeplinking"
application_url = "https://extract-bored-cabin-guys.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "bruhdev.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://extract-bored-cabin-guys.trycloudflare.com/auth/callback",
  "https://extract-bored-cabin-guys.trycloudflare.com/auth/shopify/callback",
  "https://extract-bored-cabin-guys.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

[pos]
embedded = false
