# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "wishlist-tutorial-react"
client_id = "15bce96eecd7a8914f3d499aafc45190"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[webhooks]
api_version = "unstable"

[pos]
embedded = false
