# [START config.setup-collection-details]
[[extensions]]
name = "t:collection_name"
uid = "aff2d787-08fb-5b20-9ff8-08f1d91dda8c86f44aa3"
type = "editor_extension_collection"
handle = "wishlist-management"
# [END config.setup-collection-details]


# [START config.setup-includes]
includes=["wishlist-extension-preact", "wishlist-profile-block"]
# [END config.setup-includes]

# You can also add extensions to the collection this way
#[[extensions.include]]
#handle=""

# A second editor extension collection added in the same extension toml config
# [[extensions]]
# name = "t:collection_two_name"
# type = "editor_extension_collection"
# handle = "editor-extension-collection"
# includes=[]
