# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "ca-metafields"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2025-10"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_customers, customer_write_customers"

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[customer.metafields.app.nickname]
type = "single_line_text_field"
name = "The customer's preferred name"
description = "The customer's preferred nickname for personalization"
access.customer_account = "read_write"
access.admin = "merchant_read"