api_version = "2025-10"

[[extensions]]
name = "ca-loyalty-order-status-block"
handle = "ca-loyalty-order-status-block"
type = "ui_extension"

# [START config.setup-targets]
[[extensions.targeting]]
module = "./src/PointsBlockExtension.jsx"
target = "customer-account.order-status.block.render"
# [END config.setup-targets]

[extensions.capabilities]
api_access = true
