api_version = "2024-10"

[[extensions]]
type = "ui_extension"
name = "customer-account-pre-auth-loyalty-js"
handle = "pre-auth-loyalty-extension-js"

# [START config.setup-targets]
[[extensions.targeting]]
module = "./src/BlockLoyaltyExtension.js"
target = "customer-account.order-status.block.render"
# [END config.setup-targets]

[extensions.capabilities]
# api_access = true
