api_version = "2024-10"

[[extensions]]
type = "ui_extension"
name = "My wishlist"
handle = "wishlist-extension-react"

# [START config.setup-targets]
[[extensions.targeting]]
module = "./src/FullPageExtension.tsx"
target = "customer-account.page.render"
# [END config.setup-targets]

# [START config.api-access]
[extensions.capabilities]
api_access = true
# [END config.api-access]
