api_version = "2025-10"

[[extensions]]
uid = "a1eb23c4-ce29-1e17-8061-132bf7a545b9d9bca54d"
type = "ui_extension"
name = "Upsell banner"
handle = "wishlist-profile-block"

# [START config.setup-targets]
[[extensions.targeting]]
module = "./src/ProfileBlockExtension.jsx"
target = "customer-account.profile.block.render"
# [END config.setup-targets]

[extensions.capabilities]
api_access = true
