api_version = "2025-10"

[[extensions]]
uid = "9a9cc029-b449-d82d-d072-f613da8fa52aa33c4be4"
type = "ui_extension"
name = "ca-loyalty-order-status-fulfillment"
handle = "ca-loyalty-order-status-fulfillment"

# [START config.setup-targets]
[[extensions.targeting]]
module = "./src/FulfillmentDelivery.jsx"
target = "customer-account.order-status.fulfillment-details.render-after"
# [END config.setup-targets]

[extensions.capabilities]
api_access = true