api_version = "2025-10"

[[extensions]]
type = "ui_extension"
name = "ca-loyalty-profile-block"
handle = "ca-loyalty-profile-block"


# [START config.setup-targets]
[[extensions.targeting]]
module = "./src/ProfileBlockExtension.jsx"
target = "customer-account.profile.block.render"
# [END config.setup-targets]

[extensions.capabilities]
api_access = true
